src/Entity/BankAccount.php
<?php

namespace App\Entity;

use App\Entity\Contracts\DBElementInterface;
use App\Entity\Contracts\NamedElementInterface;
use App\Entity\Contracts\TimestampedElementInterface;
use App\Repository\BankAccountRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This entity describes an bank account that the StuRa has control over.
 * It can be associated with an department.
 *
 *
 * @see \App\Tests\Entity\BankAccountTest
 */
#[ORM\Entity(repositoryClass: BankAccountRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['name'])]
#[UniqueEntity(fields: ['iban'])]
#[ORM\Table('bank_accounts')]
class BankAccount implements DBElementInterface, NamedElementInterface, TimestampedElementInterface, \Stringable
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\NotBlank]
    private string $name = '';

    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\Iban]
    private string $iban = '';

    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\Bic(ibanPropertyPath: 'iban')]
    #[Assert\NotBlank]
    private string $bic = '';

    #[ORM\Column(type: Types::TEXT)]
    private string $comment = '';

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $account_name = '';

    /**
     * @var Collection<Department>
     */
    #[ORM\OneToMany(mappedBy: 'bank_account', targetEntity: Department::class)]
    private Collection $associated_departments;

    public function __construct()
    {
        $this->associated_departments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Returns the name with which the bank account is referred in the system.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets the name with which the bank account is referred in the system.
     * Must be unique for all bank accounts.
     *
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets the IBAN associated with this bank account and which will be used in XML exports.
     */
    public function getIban(): ?string
    {
        return $this->iban;
    }

    /**
     * @return string|null The IBAN formatted with spaces between every 4 characters.
     */
    public function getIbanFormatted(): string
    {
        return chunk_split($this->iban ?? '', 4, ' ');
    }

    /**
     * Returns the IBAN of the bank account without spaces.
     * This is useful for SEPA exporter and other places where a IBAN in a machine-readable form is needed.
     */
    public function getIbanWithoutSpaces(): string
    {
        return str_replace(' ', '', $this->getIban());
    }

    /**
     * Sets the IBAN associated with this bank account and which will be used in XML exports.
     * Must be unique for all bank accounts.
     *
     * @return $this
     */
    public function setIban(string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }

    /**
     * Gets the BIC associated with this bank account and which will be used in XML exports.
     */
    public function getBic(): string
    {
        return $this->bic;
    }

    /**
     * Sets the BIC associated with this bank account and which will be used in XML exports.
     *
     * @return $this
     */
    public function setBic(string $bic): self
    {
        $this->bic = $bic;

        return $this;
    }

    /**
     * Return the name of the bank account that can be used in XML exports.
     * Can return a empty string.
     */
    public function getAccountName(): string
    {
        return $this->account_name;
    }

    /**
     * Sets the name of the bank account that can be used in XML exports.
     * Can be an empty string.
     *
     * @return $this
     */
    public function setAccountName(string $account_name): self
    {
        $this->account_name = $account_name;

        return $this;
    }

    /**
     * Returns the name that will be used in SEPA XML export for the "Account owner field".
     * This is Account name if defined, otherwise the normal name field is used.
     */
    public function getExportAccountName(): string
    {
        if (trim((string) $this->account_name) !== '') {
            return $this->account_name;
        }

        return $this->name;
    }

    /**
     * Return a comment that can be used to describe this bank account more detailed.
     */
    public function getComment(): string
    {
        return $this->comment;
    }

    /**
     * Return a comment that can be used to describe this bank account more detailed.
     *
     * @return $this
     */
    public function setComment(string $new_comment): BankAccount
    {
        $this->comment = $new_comment;

        return $this;
    }

    /**
     * A __toString() function which is used to generate a user-friendly representation of this object in drop-downs.
     */
    public function __toString(): string
    {
        return ($this->name ?? 'unknown').' ['.$this->iban.']';
    }
}

src/Entity/FundingApplication.php
<?php
/*
 * Copyright (C) 2020  Jan Böhmer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Entity;


use App\Entity\Contracts\DBElementInterface;
use App\Entity\Contracts\TimestampedElementInterface;
use App\Entity\Embeddable\Address;
use App\Entity\Embeddable\FundingID;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Entity\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use App\Repository\FundingApplicationRepository;

/**
 * @ORM\Entity(repositoryClass=FundingApplicationRepository::class)
 * @ORM\Table(
 *      name="funding_applications",
 *      uniqueConstraints={@ORM\UniqueConstraint(name="funding_id_idx", columns={"funding_id_external_funding", "funding_id_number", "funding_id_year_part"})},
 *      indexes={
            @ORM\Index(name="search_funding_id_idx", columns={"funding_id_external_funding", "funding_id_year_part"})
 *     }
 * )
 * @ORM\EntityListeners({"App\Doctrine\FundingIDGeneratorListener"})
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks()
 */
class FundingApplication implements DBElementInterface, TimestampedElementInterface
{
    use TimestampTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * The assigned funding ID of this application (e.g. M-123-21/22 or FA-123-21/22).
     * This value is filled by an entity listener before persist.
     * @ORM\Embedded(class="App\Entity\Embeddable\FundingID", columnPrefix="funding_id_")
     * @var FundingID|null
     */
    private $funding_id = null;

    /**
     * @var bool This is used to store that this is an external funding, until we fill in the funding ID in onPersist.
     */
    private $tmp_external_funding = false;

    /**
     * @ORM\Column(type="string", nullable=false)
     * @Assert\NotBlank()
     * @var string
     */
    private $applicant_name = "";

    /**
     * @var string The email address of the applicant
     * @ORM\Column(type="string", nullable=false)
     * @Assert\NotBlank()
     * @Assert\Email
     */
    private $applicant_email = "";

    /**
     * @var Department|null The organisation which apply for funding.
     * @ORM\ManyToOne(targetEntity="App\Entity\Department")
     * @Assert\NotNull(groups={"internal_funding_application"})
     * @Assert\IsNull(groups={"external_funding_application"})
     */
    private $applicant_department = null;

    /**
     * @var string|null The name of the external organsisation which applied for funding. Only needed for external funding.
     * @ORM\Column(type="string", nullable=true)
     * @Assert\NotBlank(groups={"external_funding_application"})
     * @Assert\IsNull(groups={"internal_funding_application"})
     */
    private $applicant_organisation_name = null;

    /**
     * @var string|null The phone number of the applicant. Only used in external funding.
     * @ORM\Column(type="string", nullable=true)
     */
    private $applicant_phone = null;

    /**
     * @var Address The address of the external organisation. Only needed for external funding.
     * @ORM\Embedded("App\Entity\Embeddable\Address")
     * @Assert\Valid(groups={"external_funding_application"})
     */
    private $applicant_address = null;

    /**
     * The originally requested amount of funding in (euro)cents.
     * @Assert\GreaterThan(0)
     * @var int|null
     * @ORM\Column(type="integer", nullable=false)
     */
    private $requested_amount = null;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", nullable=false)
     * @Assert\NotBlank
     * @var string|null A short description for which the requested money is intended to use.
     */
    private $funding_intention = null;

    /**
     * @Vich\UploadableField(mapping="funding_application_explanation", fileNameProperty="explanation.name", size="explanation.size", mimeType="explanation.mimeType", originalName="explanation.originalName", dimensions="explanation.dimensions")
     * @var \Symfony\Component\HttpFoundation\File\File|null
     * @Assert\File(
     *     maxSize = "1024k",
     *     mimeTypes = {"application/pdf", "application/x-pdf"},
     *     mimeTypesMessage = "validator.upload_pdf"
     * )
     */
    private $explanation_file;

    /**
     * @ORM\Embedded(class="Vich\UploaderBundle\Entity\File")
     * @var File
     */
    private $explanation;

    /**
     * @Vich\UploadableField(mapping="funding_application_finance_plan", fileNameProperty="finance_plan.name", size="finance_plan.size", mimeType="finance_plan.mimeType", originalName="finance_plan.originalName", dimensions="finance_plan.dimensions")
     *
     * @var \Symfony\Component\HttpFoundation\File\File|null
     * @Assert\NotBlank(groups={"frontend"})
     * @Assert\File(
     *     maxSize = "10M",
     *     mimeTypes = {"application/pdf", "application/x-pdf"},
     *     mimeTypesMessage = "validator.upload_pdf"
     * )
     */
    private $finance_plan_file;

    /**
     * @ORM\Embedded(class="Vich\UploaderBundle\Entity\File")
     *
     * @var File
     */
    private $finance_plan;

    public function __construct()
    {
        $this->applicant_address = new Address();
        $this->explanation = new File();
        $this->finance_plan = new File();
    }

    /**
     * Returns the funding ID assigned to this funding ID (e.g. M-123-21/22 or FA-123-21/22).
     * This is the ID shown to users instead of our internal databse ID.
     * The ID is set in an EntityListener before persisting.
     * @return FundingID|null
     */
    public function getFundingId(): ?FundingID
    {
        return $this->funding_id;
    }

    /**
     * Sets the funding ID assigned to this funding ID (e.g. M-123-21/22 or FA-123-21/22).
     * This is the ID shown to users instead of our internal databse ID.
     * The ID is set in an EntityListener before persisting, you can not call this function after the ID was already set.
     * @param  FundingID  $funding_id
     * @return FundingApplication
     */
    public function setFundingId(FundingID $funding_id): FundingApplication
    {
        if ($this->funding_id !== null) {
            throw new \LogicException("You can not change the funding ID after it was set!");
        }

        $this->funding_id = $funding_id;
        return $this;
    }

    /**
     * Returns whether this is an application of funding of an external organisation.
     * @return bool
     */
    public function isExternalFunding(): bool
    {
        if ($this->funding_id) {
            return $this->funding_id->isExternalFunding();
        }
        return $this->tmp_external_funding;
    }

    /**
     * Sets whether this is an application of funding of an external organisation.
     * @param  bool  $external_funding
     * @return FundingApplication
     */
    public function setExternalFunding(bool $external_funding): FundingApplication
    {
        if ($this->funding_id !== null) {
            throw new \LogicException("You can not change the funding type after it was set!");
        }

        $this->tmp_external_funding = $external_funding;
        return $this;
    }

    /**
     * Returns the name of the person which submitted the application.
     * @return string
     */
    public function getApplicantName(): string
    {
        return $this->applicant_name;
    }

    /**
     * Sets the name of the person which submitted the application.
     * @param  string  $applicant_name
     * @return FundingApplication
     */
    public function setApplicantName(string $applicant_name): FundingApplication
    {
        $this->applicant_name = $applicant_name;
        return $this;
    }

    /**
     * Returns the email address of the person which submitted the application.
     * @return string
     */
    public function getApplicantEmail(): string
    {
        return $this->applicant_email;
    }

    /**
     * Sets the email address of the person which submitted the application.
     * @param  string  $applicant_email
     * @return FundingApplication
     */
    public function setApplicantEmail(string $applicant_email): FundingApplication
    {
        $this->applicant_email = $applicant_email;
        return $this;
    }

    /**
     * Returns the department for which the funding application is submitted.
     * Only used for internal funding applications. For external applications applicant_organisation_name is used and this function returns null.
     * @return Department|null
     */
    public function getApplicantDepartment(): ?Department
    {
        return $this->applicant_department;
    }

    /**
     * Sets the department for which the funding application is submitted.
     * Only used for internal funding applications. For external applications applicant_organisation_name is used and this value must be null.
     * @param  Department|null  $applicant_department
     * @return FundingApplication
     */
    public function setApplicantDepartment(?Department $applicant_department): FundingApplication
    {
        $this->applicant_department = $applicant_department;
        return $this;
    }

    /**
     * Returns the name of the external organisation which applied for funding.

src/Entity/TimestampTrait.php
<?php
/*
 * Copyright (C) 2020  Jan Böhmer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Entity;

use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\HasLifecycleCallbacks()
 */
trait TimestampTrait
{
    /**
     * @var DateTime|null the date when this element was modified the last time
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, options: ['default' => 'CURRENT_TIMESTAMP'])]
    protected ?\DateTime $last_modified = null;

    /**
     * @var DateTime|null the date when this element was created
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, options: ['default' => 'CURRENT_TIMESTAMP'])]
    protected ?\DateTime $creation_date = null;

    /**
     * Helper for updating the timestamp. It is automatically called by doctrine before persisting.
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function updateTimestamps(): void
    {
        $this->last_modified = new DateTime('now');
        if (null === $this->creation_date) {
            $this->creation_date = new DateTime('now');
        }
    }

    /**
     * Returns the datetime this element was created. Returns null, if it was not persisted yet.
     */
    public function getCreationDate(): ?DateTime
    {
        return $this->creation_date;
    }

    /**
     * Returns the datetime this element was last time modified. Returns null, if it was not persisted yet.
     */
    public function getLastModified(): ?DateTime
    {
        return $this->last_modified;
    }
}

templates/pdf/payment_order/confirmations.macro.twig
{% macro signature(left, bottom) %}
    <div class="signature-area" style="margin-top: 20mm;">
        <span style="display: inline;">{{ left }}</span>
        <div style="border-top: solid 0.2mm black; margin-left: 80mm;">{{ bottom }}</div>
    </div>
{% endmacro %}

{% macro confirmation_signature(confirmation) %}
    {# @var confirmation \App\Entity\Embeddable\Confirmation #}
    {% if confirmation.confirmed %}
        {{ _self.signature("Bestätigt: " ~ confirmation.timestamp | format_datetime("short"), confirmation.confirmerName) }}
    {% else %}
        {{ _self.signature("Datum", "Unterschrift") }}
    {% endif %}
{% endmacro %}

templates/pdf/payment_order/payment_order.html.twig
{% extends "pdf/form.html.twig" %}
{% import "pdf/payment_order/confirmations.macro.twig" as confirmations %}

{# @var paymentOrder \App\Entity\PaymentOrder #}

{% macro valOrNull(value) %}
    {% if value %}
        {{ value }}
    {% else %}
        -
    {% endif %}
{% endmacro %}

{% block title %}
    Zahlungsauftrag {{ paymentOrder.iDString }}
{% endblock %}

{% block header %}
    <span style="float: left;">Zahlungsauftrag <b>{{ paymentOrder.iDString }}</b></span>
    <span style="float: right;">Formular erzeugt {{ "now"|format_datetime("short") }}</span>
{% endblock %}

{% block content %}
    {# Title section #}
    <p style="line-height: 1.0; font-weight: normal; margin-top: 0; margin-bottom: 1mm;">
        <span style="font-size: 14pt; color: #848484;">Zahlungsauftrag</span><br>
        <b style="font-size: 26pt;">{{ paymentOrder.iDString }}</b><br>
        <i style="font-size: 13pt;">{{ paymentOrder.projectName|u.truncate(60)  }}</i>
    </p>

    {# Data section #}
    <hr>

    <table class="table-form">
        <tr>
            <td>Name Auftraggeber:</td>
            <td>{{ paymentOrder.submitterName }}</td>
        </tr>
        <tr>
            <td>Struktur:</td>
            <td>{{ paymentOrder.department.name }}</td>
        </tr>

        <tr class="spacer"><td></td><td></td></tr>

        <tr>
            <td>Projektbezeichnung:</td>
            <td>{{ paymentOrder.projectName }}</td>
        </tr>

        <tr class="spacer"><td></td><td></td></tr>

        <tr>
            <td>Mittelfreigabe / Finanzantrag:</td>
            <td>{{ _self.valOrNull(paymentOrder.fundingId) }} {% if paymentOrder.resolutionDate %}({{ paymentOrder.resolutionDate | format_date }}){% endif %}</td>
        </tr>
        <tr>
            <td>Gesamtbetrag:</td>
            <td>{{ (paymentOrder.amount/100) | format_currency("EUR") }}</td>
        </tr>
        <tr>
            <td>Unterstützende Mittelfreigabe:</td>
            <td>{{ _self.valOrNull(paymentOrder.supportingFundingId) }} (TODO Beschlussdatum)</td>
        </tr>
        <tr>
            <td>Unterstützter Betrag:</td>
            <td>{% if paymentOrder.supportingAmount %}{{ (paymentOrder.supportingAmount / 100) | format_currency("EUR") }}{% else %}-{% endif %}</td>
        </tr>

        <tr class="spacer"><td></td><td></td></tr>

        <tr>
            <td>Zahlungsempfänger*in:</td>
            <td>{{ paymentOrder.bankInfo.accountOwner }}</td>
        </tr>
        <tr>
            <td>Anschrift:</td>
            <td>{{ paymentOrder.bankInfo.address }}</td>
        </tr>

        <tr class="spacer"><td></td><td></td></tr>

        <tr>
            <td>IBAN:</td>
            <td>{{ paymentOrder.bankInfo.ibanFormatted }}</td>
        </tr>
        <tr>
            <td>Verwendungszweck:</td>
            <td>{{ paymentOrder.bankInfo.reference }}</td>
        </tr>
    </table>


    <p style="text-align: center; font-weight: bold; border: black solid 1px; padding-bottom: 2px;">
        Dieses Dokument muss erst ausgedruckt, dann unterschrieben und anschließend mit allen
        nicht digital vorliegenden Originalbelegen bei den StuRa-Finanzen abgegeben werden!
    </p>

    {# Confirmation section #}
    <hr>
    <h3 style="margin: 0;">Bestätigungen ({{ paymentOrder.numberOfConfirmations }} / {{ paymentOrder.requiredConfirmations }})</h3>
    <span>Eingereicht: {{ paymentOrder.creationDate | format_datetime("short") }}</span>

    {{ confirmations.confirmation_signature(paymentOrder.confirmation1) }}
    {% if paymentOrder.requiredConfirmations > 1 %}
        {{ confirmations.confirmation_signature(paymentOrder.confirmation2) }}
    {% endif %}
{% endblock %}

{% block footer %}
    <p style="margin: 0;">
       Fettgedruckte Werte weisen darauf hin, dass dieses Feld von den StuRa-Finanzer*innen bearbeitet wurde.<br>
        Die letzte Änderung erfolgte <i>TODO Datum</i> durch <i>TOOD Finanzername</i>.
    </p>
{% endblock %}