src/Entity/User.php
<?php
/*
 * Copyright (C) 2020  Jan Böhmer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Entity;

use App\Entity\Contracts\DBElementInterface;
use App\Repository\UserRepository;
use App\Validator\NoLockout;
use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Scheb\TwoFactorBundle\Model\BackupCodeInterface;
use Scheb\TwoFactorBundle\Model\Google\TwoFactorInterface;
use Scheb\TwoFactorBundle\Model\TrustedDeviceInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This entity describes a user that can login to the backend system (it needs an ROLE_ADMIN role however).
 * The login is done with the username and a user choosable password. It is possible to configure two factor authentication
 * methods for additional security.
 *
 * @see \App\Tests\Entity\UserTest
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'])]
#[NoLockout(groups: ['perm_edit'])]
class User implements DBElementInterface, UserInterface, TwoFactorInterface, BackupCodeInterface, TrustedDeviceInterface, PasswordAuthenticatedUserInterface, \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column(type: Types::STRING)]
    private string $role_description = '';

    #[Assert\Email]
    #[ORM\Column(type: Types::STRING)]
    private string $email = '';

    #[ORM\Column(type: Types::JSON)]
    private array $roles = ['ROLE_ADMIN'];

    #[ORM\Column(type: Types::STRING)]
    private string $first_name = '';

    #[ORM\Column(type: Types::STRING)]
    private string $last_name = '';

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: Types::STRING)]
    private ?string $password = null;

    #[Assert\Length(min: 6)]
    private ?string $plain_password = null;

    #[ORM\Column(name: 'googleAuthenticatorSecret', type: Types::STRING, nullable: true)]
    private ?string $googleAuthenticatorSecret = null;

    #[ORM\Column(type: Types::INTEGER)]
    private int $trustedVersion = 0;

    #[ORM\Column(type: Types::JSON)]
    private array $backupCodes = [];

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $backupCodesDate = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * The name that is used to internally identify this user. Also used as login name.
     * Must be unique for all users.
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * Returns unique user identifier (the username)
     * @return string
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * Sets the username for this user.
     *
     * @return $this
     */
    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Returns all roles for this user.
     * Every user has at least the ROLE_USER role.
     *
     * @return string[]
     *
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * Add the given role to this user.
     *
     * @return $this
     */
    public function addRole(string $new_role): self
    {
        $this->roles[] = $new_role;
        $this->roles = array_unique($this->roles);

        return $this;
    }

    /**
     * Sets all roles for this user.
     *
     * @param string[] $roles
     *
     * @return $this
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Returns the (hashed) password for this user.
     *
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * Sets the (hashed) password for this user.
     * Should be generated with UserPasswordEncryptorInterface.
     *
     * @return $this
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Not used.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plain_password = null;
    }

    /**
     * Returns the description of what this user does or why he needs an account (the function of the user).
     */
    public function getRoleDescription(): string
    {
        return $this->role_description;
    }

    /**
     * Sets the description of what this user does or why he needs an account (the function of the user).
     */
    public function setRoleDescription(string $role_description): User
    {
        $this->role_description = $role_description;

        return $this;
    }

    /**
     * Returns the email of this user.
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Sets the email of this user.
     */
    public function setEmail(string $email): User
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Return the first name of this user.
     */
    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    /**
     * Sets the first name of this user.
     */
    public function setFirstName(string $first_name): User
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * Returns the last name of this user.
     */
    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    /**
     * Sets the last name of this user.
     */
    public function setLastName(string $last_name): User
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * Returns the full name of this user (in the format "first_name last_name").
     */
    public function getFullName(): string
    {
        if ($this->getFirstName() === null || $this->getFirstName() === '' || $this->getFirstName() === '0') {
            return $this->getLastName();
        }
        if ($this->getLastName() === null || $this->getLastName() === '' || $this->getLastName() === '0') {
            return $this->getFirstName();
        }

        return $this->getFirstName().' '.$this->getLastName();
    }

    /**
     * Returns the temporary saved plain password. We need this to set a password via EasyAdmin interface.
     * A value is only available shortly after it was set via setPlainPassword() and is deleted by eraseCredentials().
     *
     * @return string
     */
    public function getPlainPassword(): ?string
    {
        return $this->plain_password;
    }

    /**
     * Sets the temporary saved plain password. We need this to set a password via EasyAdmin interface.
     * The value is deleted by eraseCredentials().
     *
     * @param string $plainPassword
     */
    public function setPlainPassword(?string $plainPassword): User
    {
        $this->plain_password = $plainPassword;

        return $this;
    }

    /**
     * Returns true if this user has any Two-Factor method enabled.
     */
    public function isTFAEnabled(): bool
    {
        return $this->isGoogleAuthenticatorEnabled();
    }

    /**
     * Returns true if this user has google authentication 2FA enabled.
     */
    public function isGoogleAuthenticatorEnabled(): bool
    {
        return (bool) $this->googleAuthenticatorSecret;
    }

    /**
     * Returns the username that should be shown to the user for this service, when using google authenticator.
     * Here the standard username is used.
     */
    public function getGoogleAuthenticatorUsername(): string
    {
        return $this->username;
    }

    /**
     * Returns the secret used for google authenticator 2FA.
     */
    public function getGoogleAuthenticatorSecret(): ?string
    {
        return $this->googleAuthenticatorSecret;
    }

    /**
     * Sets the secred used for google authenticator 2FA.
     *
     * @return $this
     */
    public function setGoogleAuthenticatorSecret(?string $googleAuthenticatorSecret): self
    {
        $this->googleAuthenticatorSecret = $googleAuthenticatorSecret;

        return $this;
    }

    /**
     * Returns the trusted token version used to implement trusted device 2FA.
     */
    public function getTrustedTokenVersion(): int
    {
        return $this->trustedVersion;
    }

    /**
     * Invalidate all trusted devices used by this user.
     *
     * @return $this
     */
    public function invalidateTrustedDevices(): self

templates/pdf/_base_styles.css.twig
:root {
    --body-margin-left: 20mm;
    --body-margin-right: 20mm;
    --body-margin-top: 20mm;
    --body-margin-bottom: 5mm;
}

@page {
    margin: 0;
    padding: 0;
}

body {
    /*font-family: "DejaVu Sans";*/
    font-family: 'RobotoCondensed', "DejaVu Sans";
    font-size: 12pt;
}

main {
    margin: var(--body-margin-top) var(--body-margin-right) var(--body-margin-bottom) var(--body-margin-left);
}

div.page-third1 {
    position: fixed;
    top: 0;
    left: 0;
    width: 210mm;
    height: 105mm;
    padding: 5mm 22mm;
}

div.page-third2 {
    position: fixed;
    top: 105mm;
    left: 0;
    width: 210mm;
    height: 100mm;
    padding: 5mm 22mm;
}

div.page-third3 {
    position: fixed;
    top: 205mm;
    left: 0;
    width: 210mm;
    height: 92mm;
    padding: 5mm 22mm;
}

div.fold-mark {
    position: fixed;
    top: 105mm;
    left: 4mm;
    width: 4mm;
    height: 0;
    border: 0;
    border-top: 0.1mm solid black;
}

div.fold-mark2 {
    position: fixed;
    top: 205mm;
    left: 4mm;
    width: 4mm;
    height: 0;
    border: 0;
    border-top: 0.1mm solid black;
}

div.center-mark {
    position: fixed;
    top: calc(297mm/2);
    left: 4mm;
    width: 6mm;
    height: 0;
    border: 0;
    border-top: 0.1mm solid black;
}

header.header-line {
    position: absolute;
    top: 8mm;
    left: var(--body-margin-left);
    right: var(--body-margin-right);
    font-size: 9pt;
    color: #848484;
    padding-right: 0;
}

footer.footer-line {
    position: fixed;
    bottom: 8mm;
    left: var(--body-margin-left);
    right: var(--body-margin-right);
    font-size: 9pt;
    color: #848484;
}

.hint-text {
    color: #848484;
    font-size: 6pt;
    font-weight: lighter;
}

.border {
    border: solid 0.3mm black;
    padding: 0 3mm;
}

div.address-field {
    position: absolute;
    top: 45mm;
    left: 17mm;
    height: 45mm;
    width: 85mm;
    font-size: 11pt;
    line-height: 1.0;
}

div.address-field > div.return-address-zone {
    position: absolute;
    top: 2mm;
    left: 5mm;
    width: 80mm;
    height: 5mm;
    font-size: 7pt;
    border-bottom: 0.2mm solid black;

}

div.address-field > div.comment-zone {
    position: absolute;
    top: 5mm;
    left: 5mm;
    width: 80mm;
    height: 12.7mm;
}

div.address-field > div.address-zone {
    position: absolute;
    top: 12.0mm;
    left: 5mm;
    width: 80mm;
    height: 27.3mm;
}

hr {
    border: 0.1mm solid black;
    margin: 0;
}

.watermark {
    position: absolute;
    top: 30%;
    z-index: -10000;
    color: #ededed;
    font-size: 120px;
    transform: rotate(300deg);
    text-align: center;
    line-height: 1.0;
}

templates/pdf/_form_styles.css.twig
table.table-form {
    width: 100%;
    border: none;
    line-height: 1.1;
}



table.table-form td:first-child {
    font-weight: bold;
    width: 50mm;
}

table tr.spacer td { height: 1em; }

templates/pdf/base.html.twig
<html lang="de">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="author" content="StuRa-Zahlungsauftragssystem by Jan Böhmer">
    <style>
        {% include "pdf/_base_styles.css.twig" %}
        {% block styles %}{% endblock styles %}
    </style>
</head>
<body>

{# Load some umlauts hiddenly, this prevents ß to be rendered as ?? later #}
<span style="display: none;">äöüß</span>

{% if not is_productive %}
    <div class="watermark">
        TESTING<br>
        <small style="font-size: 64pt;">{{ app_version(true) }}</small>
    </div>
{% endif %}

{% block body %}{% endblock body %}
</body>
</html>

templates/pdf/form.html.twig
{% extends "pdf/header_footer.html.twig" %}

{% block styles %}
    {{ parent() }}
    {{ include("pdf/_form_styles.css.twig") }}
{% endblock %}

{% block main %}



    {# Marks on the sides for center and folding #}
    <div class="fold-mark"></div>
    <div class="center-mark"></div>
    <div class="fold-mark2"></div>

    <aside style="float: right;">
        <div style="line-height: 0.8; display: inline-block;">
            <b>Studierendenschaft der FSU Jena</b><br>
            Finanzen des Studierendenrates<br>
            Carl-Zeiss-Straße 3<br>
            07743 Jena
        </div>
        <img style="height: 20mm;" src="{{ include('pdf/StuRa-Logo.svg.base64') }}">
    </aside>

    {% block content %}

    {% endblock %}

{% endblock %}

templates/pdf/header_footer.html.twig
{% extends "pdf/base.html.twig" %}

{% block body %}
    <header class="header-line">
        {% block header %}{% endblock %}
    </header>

    {% block before_main %}{% endblock %}

    <main>
        {% block main %}{% endblock %}
    </main>

    {% block after_main %}{% endblock %}

    <footer class="footer-line">
        {% block footer %}{% endblock %}
    </footer>
{% endblock %}

templates/pdf/pdf_helpers.html.twig
{% macro signature_field(name, date, city) %}
    <span>
        <div style="display: inline;">{{ city }}, {{ date | format_date }}</div>
        <div style="margin-left: 3mm; font-size: smaller; display: inline-block; vertical-align: bottom;">_____________________________________________________________ <br>{{ name }}</div>
    </span>
{% endmacro %}

templates/pdf/template.html.twig
{% extends "pdf/base.html.twig" %}

{% block title %}{% if block("form_name") is defined and block("form_name") is not empty %}{{ block("form_name") }}{% endif %}{% endblock %}

{% block body %}
    <header class="">
        {% block header %}
            <span class="left">{% block header_left %}{% block form_name %}{% endblock %}{% endblock %}</span>
            <span class="right">{% block header_right %}{% block student_council_name %}{{ app_student_council_name }}{% endblock %}{% endblock %}</span>
            <div class="clear"></div>
        {% endblock %}
    </header>
    <footer>
        {% block footer %}
            <span class="left">Erzeugt <i>{{ 'now'|format_datetime }}</i> von <i>{{ app.user.fullName ?? '???' }}</i> (<i>@{{ app.user.userIdentifier ?? '???' }}</i>) durch {{ app_title_version }}</span>
            <span class="right"><span class="page-number">Seite </span></span>
            <div class="clear"></div>
        {% endblock %}
    </footer>
    <main>{% block main %}{% endblock %}</main>
{% endblock %}

templates/pdf/template_landscape.html.twig
{% extends "pdf/template.html.twig" %}

{% block styles %}
    {% include "pdf/css/_styles_landscape.css.twig" %}
{% endblock %}